# Generated by Django 3.1.1 on 2020-09-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_image', models.ImageField(blank=True, help_text='The image to use on the main NavBar', upload_to='', verbose_name='NavBar Image')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
